version: "3"

services:
  snow-connect-rasp:
    restart: always
    build:
      context: ./
      dockerfile: DockerfileSDK
    ports:
      - 8100:8100
  alteirac-ant-feed:
    depends_on:
    - snow-connect-rasp
    restart: always
    privileged: true
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - SOCKET_PORT= 4321
      - DEBUG=false
      - WHEEL_SIZE=4.8
      - FREQ_SENSOR=800
      - INGEST_ENABLE=true
      - HOST_STREAMING=snow-connect-rasp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4321:4321