version: "3"

services:
  alteirac-ant-feed:
    restart: always
    privileged: true
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - SOCKET_PORT= 4321
      - DEBUG=false
      - WHEEL_SIZE=2.8
      - FREQ_SENSOR=1000
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4321:4321