version: "3"

services:
  alteirac-ant-feed:
    restart: always
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - PORT= 4321
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4321:4321